---
name: 'Terratest Action'
description: 'Call Tests and get the results'
inputs:
  test:
    description: 'name of the test to run (azure)'
    required: true
outputs: {}
runs:
  using: 'composite'
  steps:
    - run: cd ${{ github.action_path }} && go test -v terratest/${{ inputs.test }}_test.go
      shell: bash
